application: updaterocker
version: 20131017
runtime: python
#threadsafe: false
api_version: 1

pagespeed:
  enabled_rewriters:
  - MinifyCss
  - InlineImages
  - CollapseWhitespace
  - ImageAddDimensions
  - RemoveComments

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$

builtins:
- remote_api: on

# libraries:
# #- name: webapp2
# #  version: "latest"
# - name: django
#   version: "1.4" #"latest"

# env_variables:
#   DJANGO_SETTINGS_MODULE: 'config'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin2/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /images/(.*)
  script: images.py

- url: /json$
  script: handler_json.py

- url: /.*
  script: static.py

